project:
  type: website
  output-dir: docs

website:
  title: "Data Science for Industry project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment.qmd
        text: Main assignment
echo:  false
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
