project:
  type: website
  output-dir: docs

website:
  title: "A Quarto Website"
  reader-mode: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment.qmd
        text: Data Science for Industry - Assignment

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
